export const licensePhrases = [
    "permission is hereby granted",
    "without warranty of any kind",
    "redistribute and use in source and binary forms",
    "licensed under the mit license",
    "spdx-license-identifier",
    "this software is proprietary",
    "copyright",
    "all rights reserved",
    "use, copy, modify, merge, publish, distribute",
    "provided that the above copyright notice",
    "subject to the following conditions",
    "warranty of merchantability or fitness",
    "MIT",
    "GNU General Public License",
    "GPL",
    "Apache License",
    "BSD License",
    "Creative Commons",
];
