export const licensePhrases = [
    "copyright",
    "license",
    "licensed",
    "licensing",

    "mit license",
    "apache license",
    "gpl",
    "bsd license",
    "isc license",
    "mozilla public license",
    "gnu general public license",
    "creative commons",

    "all rights reserved",
    "permission is hereby granted",
    "the above copyright notice",
    "this software is provided",
    "without warranty",
    "limitation of liability",
    "distributed under the terms",
    "licensed under",
    "free software foundation",
    "copyright notice",
    "copyright holder",
    "copyright owner",
    "copyright statement",
    "license agreement",
    "license terms",
    "license conditions",
    "license text",
    "license header",
    "license notice",

    "as is",
    "without any warranty",
    "express or implied",
    "including but not limited to",
    "damages arising out of",
    "use of this software",
    "use of the software",
    "use of the program",
    "use of this program",

    "mit license \\(mit\\)",
    "apache license, version 2\\.0",
    "bsd 3-clause license",
    "isc license \\(isc\\)",
    "mozilla public license 2\\.0",
    "gnu gpl",
    "gnu lgpl",
    "gnu affero gpl",

    "copyright 20",
    "copyright \\(c\\)",
    "\\(c\\) 20",
    "© 20",

    "the software",
    "this program",
    "the program",
    "source code",
    "binary form",
    "object code",
    "derivative works",
    "copies of the software",
    "copies of this software",

    "without warranty of any kind",
    "redistribute and use in source and binary forms",
    "licensed under the mit license",
    "spdx-license-identifier",
    "this software is proprietary",
    "use, copy, modify, merge, publish, distribute",
    "provided that the above copyright notice",
    "subject to the following conditions",
    "warranty of merchantability or fitness",
    "MIT",
    "GNU General Public License",
    "GPL",
    "Apache License",
    "BSD License",
    "Creative Commons",
];
